# Generated by Django 4.2.5 on 2023-09-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=0, upload_to='media'),
        ),
    ]
