# Generated by Django 4.2.5 on 2023-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=0, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(default=0, upload_to='teams'),
        ),
        migrations.AlterField(
            model_name='testominals',
            name='picture',
            field=models.ImageField(default=0, upload_to='testimonials'),
        ),
    ]
