# Generated by Django 4.2.5 on 2023-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_team_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testominals',
            name='picture',
            field=models.ImageField(default=0, upload_to='products'),
        ),
    ]
