# Generated by Django 4.2.5 on 2023-09-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_testominals_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=0, upload_to='jeehWebsite/static/images'),
        ),
    ]
